# Docker Compose configuration for development environment

services:
  database:
    image: postgres:latest
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - path: ./.env.docker
        required: true
      - path: ./.env.docker.development
        required: false
      - path: ./.env.docker.testing
        required: false
volumes:
  db_data:
    name: todo-list-ts_postgreSQL_data